### ISSUE TITLE
Setup - Capstone Project - API Based webapp

### ISSUE THREAD

**Issue by for-ashraf** [for-ashraf/Capstone-Project-2---API-based-webapp#21]
# Project Link
https://github.com/for-ashraf/Capstone-Project-2---API-based-webapp/projects/2

## Team Members ##
This is a group project of three people <a href="https://github.com/for-ashraf">Muhammad Ashraf</a>, <a href="https://github.com/AbrahaKahsay">Abraha</a> and <a href="https://github.com/lucabenaventew">Luca</a>.

**Comment by danmainah** [comment]
Hi @for-ashraf, @AbrahaKahsay and @lucabenaventew, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design

# Required Changes ♻️

- [ ] Kindly ensure all your cards are assigned to team members and the assignment is fairly done, currently, you have some cards which are unassigned
![image](https://user-images.githubusercontent.com/61408860/180846734-0c7b80b0-bf78-4a0f-8cce-e622a6d5b050.png)

 hint
Group tasks can be assigned to all members of the group


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by FrederickMih** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
